development:
  host: localhost
  port: 5432
  database: online_retail_dev
  username: postgres
  password: ${POSTGRES_PASSWORD}

test:
  host: localhost
  port: 5432
  database: online_retail_test
  username: postgres
  password: ${POSTGRES_PASSWORD}

production:
  host: ${PROD_DB_HOST}
  port: ${PROD_DB_PORT}
  database: ${PROD_DB_NAME}
  username: ${PROD_DB_USER}
  password: ${PROD_DB_PASSWORD}
